import React from 'react';
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image';

export default function Explore() {
    return (
        <div>
            <Head>
                <title>Explore | ChemLab</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='text-fontColor'>

                <div className="grid w-full py-10 place-items-center text-center">
                    <h1 className="pb-2 text-4xl font-semibold tracking-wide lg:text-6xl">
                        Select Chemical Reaction
                    </h1>
                    <div className="inline-flex h-1 bg-secondary rounded-full w-96"></div>
                </div>

                <div className="flex flex-wrap flex-col-2 justify-around w-full px-16 py-8">

                    <Link href='/dichloroethane_twist' passHref>
                        <div className="m-8">
                            <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                                <div className="pb-8 border-4  border-secondary rounded-lg">
                                    <Image width="350" height="250" src="/dichloroethane_twist.jpeg" alt="" /></div>
                                <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold">12-Dichloroethane Twist</div>
                            </div>
                        </div>
                    </Link>

                    <Link href='/pm-3m' passHref>
                        <div className="m-8">
                            <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                                <div className="pb-8 border-4  border-secondary rounded-lg">
                                    <Image width="350" height="200" src="/pm-3m.jpeg" alt="" /></div>
                                <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold">Pm-3m</div>
                            </div>
                        </div>
                    </Link>

                    <Link href='/13_butadiene_polymerization' passHref>
                        <div className="m-8">
                            <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                                <div className="pb-8 border-4  border-secondary rounded-lg">
                                    <Image width="350" height="250" src="/13_butadiene_polymerization.jpeg" alt="" /></div>
                                <div className="grid -mt-9 place-content-center mx-1 text-xl font-semibold">13 Butadiene Polymerization</div>
                            </div>
                        </div>
                    </Link>

                    <Link href='/chair_flip_for_methylcyclohexane' passHref>
                        <div className="m-8">
                            <div className="w-72 h-74 cursor-pointer transition duration-500 transform hover:scale-105">
                                <div className="pb-2 border-4  border-secondary rounded-lg">
                                    <Image width="350" height="250" src="/chair_flip_methylcyclohexane.jpeg" alt="" />
                                    <div className="grid text-center place-content-center mx-1 text-xl font-semibold">Chair Flip Methylcyclohexane</div>
                                </div>
                            </div>
                        </div>
                    </Link>

                    <Link href='/superimposing' passHref>
                        <div className="m-8">
                            <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105">
                                <div className="pb-2 border-4  border-secondary rounded-lg">
                                    <Image width="350" height="250" src="/superimposing.jpeg" alt="" />
                                    <div className="grid text-center place-content-center mx-1 text-xl font-semibold">Superimposing of Dichloroiodomethane</div>
                                </div>
                            </div>
                        </div>
                    </Link>

                    <div className="m-8">
                        <div className="w-72 h-72 cursor-pointer transition duration-500 transform hover:scale-105 border-4 border-secondary rounded-lg">
                            <div className="grid place-content-center text-3xl text-center items-center align-middle h-full font-semibold font-sourceSerifPro">More reactions comming soon..</div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
}
