import React from 'react';
import Head from 'next/head'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

export default function Find({ launches }) {
    return (
        <div>
            <Head>
                <title>Search | ChemAR</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                {launches.map(launch => {
                    return (
                            <h3 key={launch.id} >{ launch.mission_name }</h3>
                    )
                })}
            </div>


        </div>
    );
}

export async function getStaticProps() {
    const client = new ApolloClient({
        uri: 'https://api.spacex.land/graphql/',
        cache: new InMemoryCache()
    });

    const {data} = await client.query({
        query: gql`
        query GetLaunches {
            launchesPast(limit: 10) {
              mission_name
              launch_date_local
              launch_site {
                site_name_long
              }
              links {
                article_link
                video_link
              }
              rocket {
                rocket_name
                first_stage {
                  cores {
                    flight
                    core {
                      reuse_count
                      status
                    }
                  }
                }
                second_stage {
                  payloads {
                    payload_type
                    payload_mass_kg
                    payload_mass_lbs
                  }
                }
              }
              ships {
                name
                home_port
                image
              }
            }
          }
        `
    });


    return {
        props: {
            launches: data.launchesPast
        },
    }
}
