import React from 'react';
import Head from 'next/head'

export default function Find() {
    return (
        <div>
            <Head>
                <title>Search | ChemLab</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            
        </div>
    );
}
